// Copyright (C) 1991-2014 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 14.1 (Build Build 186 12/03/2014)
// Created on Tue Jun 20 22:10:36 2017

doublesync doublesync_inst
(
	.indata(indata_sig) ,	// input  indata_sig
	.outdata(outdata_sig) ,	// output  outdata_sig
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) 	// input  reset_sig
);

